# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 163d9b7481b46fb72e78ba5f28169a57a03f00cba89d93386fee57993ef1fd2bf5d627796631e94f36342403221f9243929d71f6c2b62b47021d71000abd4cf8

test:
  secret_key_base: 4c02a2f75dd4fee54a35716839a71cef37bab836dedfeca2648eef23d2056ef47e3bd9435d8c3e7b314414728f8b29520ea7a814650727e9a307ca2a2fe0ee04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
